cmake_minimum_required(VERSION 4.3)
project(learningDemo)

set(CMAKE_CXX_STANDARD 20)

add_executable(learningDemo main.cpp
        Source/_1_Welcome_to_CPP.cpp
        Header/_1_Welcome_to_CPP.h
        Source/_2_How_to_Setup_CPP_on_Windows.cpp
        Header/_2_How_to_Setup_CPP_on_Windows.h
        Source/_3_How_to_Setu_CPP_on_Mac.cpp
        Header/_3_How_to_Setu_CPP_on_Mac.h
        Source/_4_How_to_Setup_CPP_on_Linux.cpp
        Header/_4_How_to_Setup_CPP_on_Linux.h
        Source/_5_How_CPP_Works.cpp
        Header/_5_How_CPP_Works.h
        Source/_6_How_the_CPP_Compiler_Works.cpp
        Header/_6_How_the_CPP_Compiler_Works.h
        Source/_7_How_the_CPP_Linker_Works.cpp
        Header/_7_How_the_CPP_Linker_Works.h
        Source/_8_Variables_in_CPP.cpp
        Header/_8_Variables_in_CPP.h
        Source/_9_Functions_in_CPP.cpp
        Header/_9_Functions_in_CPP.h
        Source/_10_CPP_Header_Files.cpp
        Header/_10_CPP_Header_Files.h
        Source/_11_How_to_DEBUG_CPP_in_VISUAL_STUDIO.cpp
        Header/_11_How_to_DEBUG_CPP_in_VISUAL_STUDIO.h
        Source/_12_CONDITIONS_and_BRANCHES_in_CPP_if_statements.cpp
        Header/_12_CONDITIONS_and_BRANCHES_in_CPP_if_statements.h
        Source/_13_BEST_Visual_Studio_Setup_for_CPP_Projects.cpp
        Header/_13_BEST_Visual_Studio_Setup_for_CPP_Projects.h
        Source/_14_Loops_in_CPP_for_loops_while_loops.cpp
        Header/_14_Loops_in_CPP_for_loops_while_loops.h
        Source/_15_Control_Flow_in_CPP_continue_break_return.cpp
        Header/_15_Control_Flow_in_CPP_continue_break_return.h
        Source/_16_POINTERS_in_CPP.cpp
        Header/_16_POINTERS_in_CPP.h
        Source/_17_REFERENCES_in_CPP.cpp
        Header/_17_REFERENCES_in_CPP.h
        Source/_18_CLASSES_in_CPP.cpp
        Header/_18_CLASSES_in_CPP.h
        Source/_19_CLASSES_vs_STRUCTS_in_CPP.cpp
        Header/_19_CLASSES_vs_STRUCTS_in_CPP.h
        Source/_20_How_to_Write_a_CPP_Class.cpp
        Header/_20_How_to_Write_a_CPP_Class.h
        Source/_21_Static_in_CPP.cpp
        Header/_21_Static_in_CPP.h
        Source/_22_Static_for_Classes_and_Structs_in_CPP.cpp
        Header/_22_Static_for_Classes_and_Structs_in_CPP.h)
