//
// Created by LiMi on 2026/8/19.
//

#ifndef LEARNINGDEMO__12_CONDITIONS_AND_BRANCHES_IN_CPP_IF_STATEMENTS_H
#define LEARNINGDEMO__12_CONDITIONS_AND_BRANCHES_IN_CPP_IF_STATEMENTS_H


class _12_CONDITIONS_and_BRANCHES_in_CPP_if_statements {
public:
    static void main();
};


#endif //LEARNINGDEMO__12_CONDITIONS_AND_BRANCHES_IN_CPP_IF_STATEMENTS_H
