//
// Created by LiMi on 2026/8/20.
//

#ifndef LEARNINGDEMO__35_MEMBER_INITIALIZER_LISTS_IN_CPP_CONSTRUCTOR_INITIALIZER_LIST_H
#define LEARNINGDEMO__35_MEMBER_INITIALIZER_LISTS_IN_CPP_CONSTRUCTOR_INITIALIZER_LIST_H


class _35_Member_Initializer_Lists_in_CPP_Constructor_Initializer_List {
    public:
    static void main();
};



#endif //LEARNINGDEMO__35_MEMBER_INITIALIZER_LISTS_IN_CPP_CONSTRUCTOR_INITIALIZER_LIST_H
