//
// Created by LiMi on 2026/8/20.
//

#ifndef LEARNINGDEMO__37_HOW_TO_CREATE_INSTANTIATE_OBJECTS_IN_CPP_H
#define LEARNINGDEMO__37_HOW_TO_CREATE_INSTANTIATE_OBJECTS_IN_CPP_H


class _37_How_to_CREATE_INSTANTIATE_OBJECTS_in_CPP {
public:
    static void main();
};



#endif //LEARNINGDEMO__37_HOW_TO_CREATE_INSTANTIATE_OBJECTS_IN_CPP_H
