//
// Created by LiMi on 2026/8/21.
//

#ifndef LEARNINGDEMO__40_OPERATORS_AND_OPERATOR_OVERLOADING_IN_CPP_H
#define LEARNINGDEMO__40_OPERATORS_AND_OPERATOR_OVERLOADING_IN_CPP_H


class _40_OPERATORS_and_OPERATOR_OVERLOADING_in_CPP {
public:
    static void main();
};



#endif //LEARNINGDEMO__40_OPERATORS_AND_OPERATOR_OVERLOADING_IN_CPP_H
