//
// Created by LiMi on 2026/8/21.
//

#ifndef LEARNINGDEMO__43_SMART_POINTERS_IN_CPP_STD_UNIQUE_PTR_STD_SHARED_PTR_STD_WEAK_PTR_H
#define LEARNINGDEMO__43_SMART_POINTERS_IN_CPP_STD_UNIQUE_PTR_STD_SHARED_PTR_STD_WEAK_PTR_H


class _43_SMART_POINTERS_in_CPP_std_unique_ptr_std_shared_ptr_std_weak_ptr {
public:
    static void main();
};



#endif //LEARNINGDEMO__43_SMART_POINTERS_IN_CPP_STD_UNIQUE_PTR_STD_SHARED_PTR_STD_WEAK_PTR_H
