//
// Created by LiMi on 2026/8/22.
//

#ifndef LEARNINGDEMO__51_MAKING_AND_WORKING_WITH_LIBRARIES_IN_CPP_MULTIPLE_PROJECTS_IN_VISUAL_S_H
#define LEARNINGDEMO__51_MAKING_AND_WORKING_WITH_LIBRARIES_IN_CPP_MULTIPLE_PROJECTS_IN_VISUAL_S_H


class _51_Making_and_Working_with_Libraries_in_CPP_Multiple_Projects_in_Visual_S {
public:
    static void main();
};



#endif //LEARNINGDEMO__51_MAKING_AND_WORKING_WITH_LIBRARIES_IN_CPP_MULTIPLE_PROJECTS_IN_VISUAL_S_H
