//
// Created by LiMi on 2026/8/25.
//

#ifndef LEARNINGDEMO__77_MULTIPLE_TYPES_OF_DATA_IN_A_SINGLE_VARIABLE_IN_CPP_H
#define LEARNINGDEMO__77_MULTIPLE_TYPES_OF_DATA_IN_A_SINGLE_VARIABLE_IN_CPP_H


class _77_Multiple_TYPES_of_Data_in_a_SINGLE_VARIABLE_in_CPP {
public:
    static void main();
};



#endif //LEARNINGDEMO__77_MULTIPLE_TYPES_OF_DATA_IN_A_SINGLE_VARIABLE_IN_CPP_H
