//
// Created by LiMi on 2026/8/25.
//

#ifndef LEARNINGDEMO__81_VISUAL_BENCHMARKING_IN_CPP_HOW_TO_MEASURE_PERFORMANCE_VISUALLY_H
#define LEARNINGDEMO__81_VISUAL_BENCHMARKING_IN_CPP_HOW_TO_MEASURE_PERFORMANCE_VISUALLY_H


class _81_VISUAL_BENCHMARKING_in_CPP_how_to_measure_performance_visually {
public:
    static void main();
};


#endif //LEARNINGDEMO__81_VISUAL_BENCHMARKING_IN_CPP_HOW_TO_MEASURE_PERFORMANCE_VISUALLY_H
