//
// Created by LiMi on 2026/8/26.
//

#ifndef LEARNINGDEMO__84_TRACK_MEMORY_ALLOCATIONS_THE_EASY_WAY_IN_CPP_H
#define LEARNINGDEMO__84_TRACK_MEMORY_ALLOCATIONS_THE_EASY_WAY_IN_CPP_H


class _84_Track_MEMORY_ALLOCATIONS_the_Easy_Way_in_CPP {
public:
    static void main();
};



#endif //LEARNINGDEMO__84_TRACK_MEMORY_ALLOCATIONS_THE_EASY_WAY_IN_CPP_H
