//
// Created by LiMi on 2026/8/28.
//

#ifndef LEARNINGDEMO__99_BEST_WAY_TO_MAKE_DESKTOP_APPLICATIONS_IN_CPP_H
#define LEARNINGDEMO__99_BEST_WAY_TO_MAKE_DESKTOP_APPLICATIONS_IN_CPP_H


class _99_BEST_WAY_to_make_Desktop_Applications_in_CPP {
public:
    static void main();
};


#endif //LEARNINGDEMO__99_BEST_WAY_TO_MAKE_DESKTOP_APPLICATIONS_IN_CPP_H
